theme: jekyll-theme-minimal
title: Daniel Zurek's Data Projects
logo: /assets/img/havi_logo.jpg
description: Collection of miscellaneous side projects. My academic research can be found at my [main site](http://danielzurek.com).
